name: CI/CD Pipeline

on:
  push:
    branches:
      - master
      - dev
      - prod
  pull_request:
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create Docker network
        run: docker network create net || true

      - name: Build web container
        run: docker build -t web .

      - name: Build test environment container
        run: docker build -t test_env -f tests/Dockerfile tests

      - name: Run web container
        run: docker run --rm --network net -p 80:80 --name web -d web

      - name: Run tests
        run: docker run --network net -e APP_HOST=web test_env

      - name: Cleanup containers
        if: always()
        run: |
          docker kill web || true
          docker kill redis || true

  deploy-dev:
    if: github.ref == 'refs/heads/dev'
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Dev
        run: echo "Deploying to Dev environment..."

  deploy-prod:
    if: github.ref == 'refs/heads/prod'
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - name: Wait for manual approval
        run: echo "Waiting for manual approval (setup environment protection rules in GitHub Settings)"
      - name: Deploy to Prod
        run: echo "Deploying to Production environment..."
