name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - dev
      - prod
  pull_request:
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build web container
        run: |
          docker build -t web .

      - name: Build test environment container
        run: |
          docker build -t test_env -f tests/Dockerfile tests

      - name: Create Docker network
        run: |
          docker network create net || true

      - name: Run web container
        run: |
          docker run --rm --network net -p 80:80 --name web -d web
          
      - name: Wait for web server to be ready
        run: |
             for i in {1..30}; do
                if curl -s http://web/ > /dev/null; then
                  echo "Web server is ready!"
                  break
                fi
                echo "Waiting for web server..."
                sleep 1
             done
             
      - name: Run tests
        run: |
          docker run --network net test_env

      - name: Cleanup containers
        if: always()
        run: |
          docker kill web || true
          docker kill redis || true

  deploy-dev:
    if: github.ref == 'refs/heads/dev'
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Dev
        run: echo "Deploying to Dev environment..."

  deploy-prod:
    if: github.ref == 'refs/heads/prod'
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - name: Wait for manual approval
        uses: fjogeleit/http-request-action@v1
        with:
          url: https://example.com/manual-approval-required
          method: 'GET'
      - name: Deploy to Prod
        run: echo "Deploying to Production environment..."
